version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: ["./stackunderflow/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/stackunderflow
    env_file:
      - ./.postgres.env
    depends_on:
      - db
  db:
    image: postgres:14.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
