# Generated by Django 2.2.10 on 2022-10-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(help_text='Date of birth in format YYYY-MM-DD', null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=50, verbose_name='profession'),
        ),
    ]
