# Generated by Django 2.2.10 on 2022-10-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0002_auto_20221026_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='question title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='detailed description of the question/issue')),
                ('upvotes', models.IntegerField(default=0, verbose_name='upvotes')),
                ('downvotes', models.IntegerField(default=0, verbose_name='downvotes')),
                ('viewcount', models.IntegerField(default=0, verbose_name='number of times question is viewed')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=7, verbose_name='question status')),
                ('closing_remark', models.CharField(choices=[('NOT_CLEAR', 'Not clear'), ('DUPLICATE', 'Duplicate question'), ('INVALID', 'Not a valid question')], max_length=10, null=True, verbose_name='question closing remark')),
            ],
        ),
    ]
