# Generated by Django 2.2.10 on 2022-10-29 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='tag name')),
                ('description', models.CharField(blank=True, max_length=20, verbose_name='description of the tag')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_body', models.TextField(verbose_name='answer body')),
                ('upvotes', models.IntegerField(default=0, verbose_name='upvotes')),
                ('downvotes', models.IntegerField(default=0, verbose_name='downvotes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='answer posted at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='answer updated at')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stack_underflow_app.Question')),
            ],
        ),
    ]
