# Generated by Django 3.2.16 on 2022-11-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0010_auto_20221030_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.BigIntegerField(default=None, verbose_name='post id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='post_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stack_underflow_app.posttype'),
        ),
    ]
