# Generated by Django 3.2.16 on 2022-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0011_auto_20221103_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='is accepted answer'),
        ),
    ]
