# Generated by Django 3.2.16 on 2022-11-13 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0012_answer_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
