# Generated by Django 3.2.16 on 2022-11-18 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0014_alter_question_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(verbose_name='Is upvote')),
                ('downvote', models.BooleanField(verbose_name='Is downvote')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack_underflow_app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'user')},
            },
        ),
    ]
