# Generated by Django 3.2.16 on 2022-11-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0015_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvotes',
        ),
    ]
