# Generated by Django 3.2.16 on 2022-11-23 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0016_auto_20221118_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='votes',
            name='post_id',
            field=models.BigIntegerField(default=-1, verbose_name='post id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votes',
            name='post_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stack_underflow_app.posttype'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='name',
            field=models.CharField(choices=[('QUESTION', 'Question'), ('ANSWER', 'Answer'), ('COMMENT', 'Comment')], default='QUESTION', max_length=10, unique=True, verbose_name='post type'),
        ),
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together={('post_id', 'post_type', 'user')},
        ),
        migrations.RemoveField(
            model_name='votes',
            name='question',
        ),
    ]
