# Generated by Django 3.2.16 on 2022-11-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0017_auto_20221123_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='post_id',
            field=models.BigIntegerField(db_index=True, verbose_name='post id'),
        ),
    ]
