# Generated by Django 3.2.16 on 2022-12-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0019_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation_points',
            field=models.IntegerField(default=0, verbose_name='reputation points'),
        ),
    ]
