# Generated by Django 3.2.16 on 2023-02-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack_underflow_app', '0020_user_reputation_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
